package org.example.bankramenserver.domain.auth.service
import org.example.bankramenserver.domain.auth.dto.response.AuthTokenResponse
import org.example.bankramenserver.domain.auth.dto.response.KakaoTokenResponse
import org.example.bankramenserver.domain.auth.dto.response.KakaoUserResponse
import org.example.bankramenserver.domain.auth.exception.KaKaoTokenRequestFailedException
import org.example.bankramenserver.domain.auth.exception.KaKaoUserInfoRequestFailedException
import org.example.bankramenserver.domain.user.service.UserService
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import org.springframework.http.*
import org.springframework.stereotype.Service
import org.springframework.util.LinkedMultiValueMap
import org.springframework.web.client.RestTemplate
import org.springframework.web.util.UriComponentsBuilder
@Service class KakaoOAuthService(private val restTemplate: RestTemplate, private val userService: UserService, private val jwtService: JwtService, private val refreshTokenService: RefreshTokenService, @Value("\${kakao.client-id}") private val clientId: String, @Value("\${kakao.redirect-uri}") private val redirectUri: String, @Value("\${kakao.auth-url}") private val authUrl: String, @Value("\${kakao.api-url}") private val apiUrl: String, @Value("\${kakao.client-secret}") private val clientSecret: String) { private val log = LoggerFactory.getLogger(javaClass); fun kakaoLogin(code: String): AuthTokenResponse { val user = userService.saveOrUpdate(getUserInfo(getAccessToken(code).accessToken)); val userId = user.id!!; val access = jwtService.generateAccessToken(userId); val refresh = jwtService.generateRefreshToken(userId); refreshTokenService.save(refresh, userId); return AuthTokenResponse(access, refresh) }; fun reissue(refreshToken: String): AuthTokenResponse { val id = jwtService.validateRefreshToken(refreshToken); refreshTokenService.validate(refreshToken, id); refreshTokenService.delete(refreshToken); val access = jwtService.generateAccessToken(id); val refresh = jwtService.generateRefreshToken(id); refreshTokenService.save(refresh, id); return AuthTokenResponse(access, refresh) }; fun logout(refreshToken: String) { val id = jwtService.validateRefreshToken(refreshToken); refreshTokenService.validate(refreshToken, id); refreshTokenService.delete(refreshToken) }; fun getLoginUrl(state: String) = UriComponentsBuilder.fromUriString(authUrl).path("/authorize").queryParam("response_type", "code").queryParam("client_id", clientId).queryParam("redirect_uri", redirectUri).queryParam("state", state).encode().toUriString(); private fun getAccessToken(code: String): KakaoTokenResponse = try { val headers = HttpHeaders().also { it.contentType = MediaType.APPLICATION_FORM_URLENCODED }; val params = LinkedMultiValueMap<String, String>().also { it.add("grant_type", "authorization_code"); it.add("client_id", clientId); it.add("redirect_uri", redirectUri); it.add("code", code); it.add("client_secret", clientSecret) }; restTemplate.postForObject("$authUrl/token", HttpEntity(params, headers), KakaoTokenResponse::class.java) ?: throw KaKaoTokenRequestFailedException.EXCEPTION } catch (e: Exception) { log.error("카카오 토큰 요청 실패", e); throw KaKaoTokenRequestFailedException.EXCEPTION }; private fun getUserInfo(accessToken: String): KakaoUserResponse = try { val headers = HttpHeaders().also { it.setBearerAuth(accessToken) }; restTemplate.exchange("$apiUrl/v2/user/me", HttpMethod.GET, HttpEntity<Void>(headers), KakaoUserResponse::class.java).body ?: throw KaKaoUserInfoRequestFailedException.EXCEPTION } catch (e: Exception) { log.error("카카오 사용자 정보 요청 실패", e); throw KaKaoUserInfoRequestFailedException.EXCEPTION } }
